apiVersion: v1
kind: Service
metadata:
  name: nginx2-svc
  labels:
    app: nginx2
spec:
  ports:
    - name: nginx2-port
      protocol: "TCP"
      port: 8081
      targetPort: nginx2-port
  selector:
    app: nginx2
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2-deployment
spec:
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx2
        image: yoshiken/kabane-demo:nginx2
        ports:
        - containerPort: 80
          name: nginx2-port
          protocol: TCP
